### ISSUE TITLE
[Feature Request] Add «hidden» link to text posts

### ISSUE THREAD

**Issue by Kondra007** [40PK/Chad#1]
When using [HTML mode](https://core.telegram.org/bots/api#formatting-options), you can place hidden link in the beginning of text to force Telegram use particular URL for Link Preview. Hidden link's format: `<a href="url">&#8203;</a>`

Maybe make optional field "Hidden link" in Chad?

**Comment by Perkovec** [comment]
Added with [cc5d88a](https://github.com/40PK/Chad/commit/cc5d88a020aebe4da43a2e00c13954f0ed55d9e1)
