### ISSUE TITLE
[Feature Request] Add private channels

### ISSUE THREAD

**Issue by Kondra007** [40PK/Chad#2]
In [Chad.jsx](https://github.com/40PK/Chad/blob/c03071f9e88f116287a9cf42497ad13de58313bf/src/content/Chad.jsx#L22) file only `@usernames` are supported via RegEx.

Since bots can post to private channels using IDs (negative numbers), please, add ability to use them.  
Now it throws

![image](https://cloud.githubusercontent.com/assets/2780044/18469845/6f45268e-79b2-11e6-8e04-60e5fdc2d914.png)

**Comment by Perkovec** [comment]
Fixed in [v3.3](https://github.com/40PK/Chad/releases/tag/v3.3)
