### ISSUE TITLE
[Bug?] Can't send posts on Windows

### ISSUE THREAD

**Issue by Kondra007** [40PK/Chad#3]
Added bot's token, added channel where bot can write, sent a simple "text" message.

**Result**: Button "send" changed title to "wait..." and message doesn't appear in channel.
**OS**: Windows 10 x64 LTSB (non-Anniversary Update)
**Chad**: for Windows x64 and for Windows x86

**Update**: Looks like 3.2 version for Windows is not really 3.2 (it looks completely differently)

**Comment by Perkovec** [comment]
Fixed in [v3.3](https://github.com/40PK/Chad/releases/tag/v3.3)
